### ISSUE TITLE
Heatmap with None produces error

### ISSUE THREAD

**Issue by guadalupebabio** [CityScope/CS_Brix#31] opened 2021-03-12 14:55 UTC
I'm trying to post a heatmap with multiple layers, with some missing values, but Brix is not posting the values correctly. 

This is how the `update_package` looks like
![image](https://user-images.githubusercontent.com/38555658/110956760-f357bf80-8318-11eb-87fb-4e78ec6a7200.png)

This is the error I'm getting
```
Performing initial update
https://cityio.media.mit.edu/api/table/lomas/GEOGRIDDATA Attempt: 0
Unrecognized types: {'Electricty_SolarPanel'}
Traceback (most recent call last):
  File "/Users/babiog/Documents/GitHub/TeraScope/TeraScope_Deployment.py", line 20, in <module>
    H.listen()
  File "/Users/babiog/myEnvs/tera/lib/python3.9/site-packages/brix/classes.py", line 1124, in listen
    self._listen(showFront=showFront)
  File "/Users/babiog/myEnvs/tera/lib/python3.9/site-packages/brix/classes.py", line 1079, in _listen
    self.perform_geogrid_data_update()
  File "/Users/babiog/myEnvs/tera/lib/python3.9/site-packages/brix/classes.py", line 1033, in perform_geogrid_data_update
    self.post_geogrid_data(new_geogrid_data)
  File "/Users/babiog/myEnvs/tera/lib/python3.9/site-packages/brix/classes.py", line 1153, in post_geogrid_data
    raise NameError('Type not found in table definition.')
NameError: Type not found in table definition.
```

**Comment by guadalupebabio** [comment] 2021-03-12 15:40
we ran into the issue that we want to post heatmaps with missing values, and we discovered that we cannot do it. Instead, we need to fill them with zeros like this example:
https://cityio.media.mit.edu/api/table/epa_test/access

**Comment by crisjf** [comment] 2021-03-12 21:09
Guada, I think the issue is not with your heatmap, but with your grid modification function. (this one https://github.com/guadalupebabio/TeraScope/blob/main/my_gridmodification.py)

Before posting the new `GEOGRIDDATA` object, brix makes sure the object is valid by running a series of tests. One test is to check whether the `type` of each cell you defined in the new object is a valid type defined when you generated the table. To do so, brix makes sure that all types are in https://cityio.media.mit.edu/api/table/lomas/GEOGRID/properties/types.

In your function, is setting some cells to `Electricty_SolarPanel` which is not found in your `GEOGRID` object. Your `GEOGRID` object has `Electricity_SolarPanel`, which is different. This error is raised to ensure your table doesn't break.

I'm gonna change some of the error messages to make this issue easier to debug, and I'll close this issue. 

I also realized that `brix` is already setting all missing values to zero anyways.

**Comment by crisjf** [comment] 2021-03-12 21:16
I'm closing this as it appears to not be a `brix` issue. We can reopen it if it turns out I was wrong :)

**Closed as completed by crisjf** 2021-03-12 21:16 UTC
